### ISSUE TITLE
Opening Any Guide via a New Tab Returns a 403 Forbidden Error

### ISSUE THREAD

**Issue by KR1dude** [zaksabeast/PokemonRNGGuides#102]
Whenever I click a guide link and open it as a new tab, the site returns a 403 Access Denied error. If I just click the guide link, I can access the page just fine. Tested on latest stable build of Google Chrome and Microsoft Edge.

**Comment by zaksabeast** [comment]
Thank you for letting me know, I really appreciate it :slightly_smiling_face: 

This issue should be resolved.  Enjoy the site!
