### ISSUE TITLE
[Site rework #1] Separation between Emu / Retails Guides in the Game's page

### ISSUE THREAD

**Issue by RichardPaulAstley** [zaksabeast/PokemonRNGGuides#105]
First idea : Leaving the navigation bar as it is but just add a separation between Emu Retails guides in the game's page

![image](https://user-images.githubusercontent.com/25870563/86136600-939fe800-baec-11ea-945a-111c75d63ab7.png)

Like this

**Comment by zaksabeast** [comment]
Closed with https://github.com/zaksabeast/PokemonRNGGuides/commit/4fc991ee7ce443dc80b054e77c7a78039e5f43ce.
