### ISSUE TITLE
[Site Rework #4] Creating "general" guides for each gen

### ISSUE THREAD

**Issue by RichardPaulAstley** [zaksabeast/PokemonRNGGuides#108]
The issue is that some guides are outdated by describing a wrong method inside. Example with wormhole guide that uses the fidgeting guide, which is INSIDE rather than explaining to use Timeleap which is an EXTERNAL guide.

My goal would be :
- To create all the basic guides in a special folder (example for Gen 7 putting all the timeline guides together)
- And saying in the specific guide which basics guides are available for your specific guide.

**Comment by ShinySylveon04** [comment]
This is currently being done with PR #124. Are there other guides this applies to?
