### ISSUE TITLE
[Site Rework #5] Editing the contribute link.

### ISSUE THREAD

**Issue by RichardPaulAstley** [zaksabeast/PokemonRNGGuides#109]
I think that some people are quite scary of github.

So we should think another way to let people to contribute to the website WITHOUT using github. Like allowing us to contact us on reddit etc.

Also, would be could to use that to link to the "RNG Listing" doc to have an idea of what is necessary / what have been done

**Comment by zaksabeast** [comment]
Was this solved with https://github.com/zaksabeast/PokemonRNGGuides/commit/6b46cdf5290d21330dcd44c9a507d65a1ce0a8ea?

**Comment by zaksabeast** [comment]
Yep!  This is closed with https://github.com/zaksabeast/PokemonRNGGuides/commit/6b46cdf5290d21330dcd44c9a507d65a1ce0a8ea.
