### ISSUE TITLE
Update links in all guides

### ISSUE THREAD

**Issue by zaksabeast** [zaksabeast/PokemonRNGGuides#110]
With recent changes, most guides that link to another guide on the site need to be updated with a new link.

This should be pretty easy to accomplish:
1. Find links to guides in the markdown files (located in the `guides` directory)
2. Find the new links that should replaced the old links
3. Replace the links

**Comment by ShinySylveon04** [comment]
Closing this issue since it looks like this was fixed with a PR. If there are still broken links, please open an issue for the guide(s) affected.
