### ISSUE TITLE
[Fix Guide] BW / BW2 How to find DS Parameters being wrong.

### ISSUE THREAD

**Issue by RichardPaulAstley** [zaksabeast/PokemonRNGGuides#114]
https://www.pokemonrng.com/emulator-bw-find-ds-parameters

^This guide.

The user didn't take care to explain how settings works, and how to  adjust them CORRECTLY
The settings shown in the screens are wrong and worth in only one case.
Not trustable, not viable.

**Comment by zaksabeast** [comment]
I agree this page could use some changes.

@RichardPaulAstley Do you have a draft branch that could be used as a base?  I didn't see one for this, but wanted to double check with you.

For anyone who might want to update this guide with more details, this is the file that would need editing: https://www.github.com/zaksabeast/PokemonRNGGuides/tree/master/guides%2FBlack%20and%20White%2FFind%20DS%20Parameters.md

**Comment by RichardPaulAstley** [comment]
Nope didn't do anything on that one.
I can edit the one on my fork, doing the necessary edits. If it's good enough writing wise we push, if not well it's a draft

**Comment by zaksabeast** [comment]
Sounds good, thanks!  If it's a draft, I'll update any pieces it needs and we can push it.

**Comment by ShinySylveon04** [comment]
Resolved with #119
