### ISSUE TITLE
Lua repo

### ISSUE THREAD

**Issue by RichardPaulAstley** [zaksabeast/PokemonRNGGuides#26]
As suggested on discord : 

Not sure if it's the right place for that, but since it'll be about pokemonrng.com, well for the moment it's the good place to talk about this.

It'd be nice to have a place to gather any kind of lua scripts, like we're gonna gather guides. Since there are the BASICS lua scripts and so much alternative (look at how many different gen 2 scripts are already done) and this way people could choose the lua they want from the repo or from the site, explaining the little differences between each

**Comment by Admiral-Fish** [comment]
https://github.com/Admiral-Fish/luascripts
