### ISSUE TITLE
Update guides for GBA Bios

### ISSUE THREAD

**Issue by ShinySylveon04** [zaksabeast/PokemonRNGGuides#96]
~~**Guide has yet to be deployed to the site, but once it is this needs to be done**~~

Guide has been added, link: https://pokemonrng.com/guides/tools/en/How%20to%20Extract%20GBA%20Bios/

Add link to the guide in the following guides:

- [ ] Wishmaker Jirachi RNG
- [ ] Connecting Dolphin to VBA

The bios is required for the two above, however it may also be needed for other types of RNG depending on the lua scripts used. The ones from NOOB do not need it, but it should be listed as a solution for troubleshooting instead of required in tools section. This way users can know how to fix the error caused by not having the file should they choose to use another lua script that requires it, or should there be a game that needed it.

The following guides need to have a troubleshooting section added/updated for the bios:

- [ ] RSE Dead Battery TID RNG
- [ ] RSE Live Battery TID RNG
- [ ] RSE Live Battery Stationary RNG
- [ ] FRLG Stationary & Gift RNG
- [ ] FRLG Wild RNG

**Comment by zaksabeast** [comment]
I'm going to close this issue since it's stale and open a new issue that includes links for all guides.  With recent changes, I have a feeling lots of links are outdated right now.
